2005-01-13  Zac Bowling  <zac@zacbowling.com>
	* makefile.win32 : new "gac" target for automatic for gacutil calls,
	added copying of gtk-sharp.snk to each folder being built to fix fresh
	builds and after cleaning, added support for switching C#
	compilers, and added handling of spaces in filenames for mcs builds
	* gtkdotnet/makefile.win32 : add one more reference to fix mcs builds.

svn path=/trunk/gtk-sharp/; revision=38893

diff --git a/makefile.win32 b/makefile.win32
--- a/makefile.win32
+++ b/makefile.win32
@@ -1,20 +1,39 @@
 DIRS=generator parser glib pango atk gdk gtk glade gtkdotnet
 ROOT=/cygdrive/$(subst \,/,$(subst :\,/,$(SYSTEMROOT)))
+#pesky spaces - blame zbowling if this fails
+PROGFILES=`cygpath \`cygpath -m -s "$(PROGRAMFILES)"\``
+
+## --- C# Compiler ---
+## Mono v1.1.3
+#CSC=$(PROGFILES)/Mono-1.1.3/bin/mcs.bat /d:WIN32
+##.NET v1.1.4322
+#CSC=$(ROOT)/microsoft.net/framework/v1.1.4322/csc.exe /d:WIN32
+##.NET v1.0.3705
 CSC=$(ROOT)/microsoft.net/framework/v1.0.3705/csc.exe /d:WIN32
+
+## --- GACUTIL ---
+## .NET gacutil
+#GACUTIL=gacutil.exe
+## Mono gacutil
+GACUTIL=gacutil.bat
+
 
 all: windows
 
 windows:
 	for i in $(DIRS); do				\
-		(cd $$i; CSC="$(CSC)" make -f makefile.win32) || exit 1;\
+		(cp gtk-sharp.snk $$i; cd $$i; CSC="$(CSC)" make -f makefile.win32) || exit 1;\
 	done;
 
 clean:
 	for i in $(DIRS); do \
 		(cd $$i; make -f makefile.win32 clean) || exit 1;\
 	done;
+	`rm -r lib` 
 
 release: clean windows
-	mkdir lib
+	`mkdir -p lib` 
 	find $(DIRS) -iname "*.dll" -exec cp \{\} lib \;
 
+gac: release
+	find -iname "*-sharp.dll" -exec $(GACUTIL) /i \{\} \;
